ALTER TABLE "dwa".geo ADD CONSTRAINT UNIQUE (g_geoid) CONSTRAINT u1;
ALTER TABLE "dwa".state ADD CONSTRAINT UNIQUE (s_stateid) CONSTRAINT u2;
ALTER TABLE "dwa".label ADD CONSTRAINT UNIQUE (l_labelid) CONSTRAINT u3;
ALTER TABLE "dwa".color ADD CONSTRAINT UNIQUE (co_colorid) CONSTRAINT u4;
ALTER TABLE "dwa".fashionitem ADD CONSTRAINT UNIQUE (f_fitemid) CONSTRAINT u5;
ALTER TABLE "dwa".designer ADD CONSTRAINT UNIQUE (d_designerid) CONSTRAINT u6;
ALTER TABLE "dwa".article ADD CONSTRAINT UNIQUE (a_artid) CONSTRAINT u7;
ALTER TABLE "dwa".supplier ADD CONSTRAINT UNIQUE (su_suppid) CONSTRAINT u8;
ALTER TABLE "dwa".inventory ADD CONSTRAINT UNIQUE (i_artid, i_suppid)
  CONSTRAINT u9;
ALTER TABLE "dwa".customer ADD CONSTRAINT UNIQUE (c_custid) CONSTRAINT u10;
ALTER TABLE "dwa".order ADD CONSTRAINT UNIQUE (o_orderid) CONSTRAINT u11;
ALTER TABLE "dwa".partlist ADD CONSTRAINT UNIQUE (p_orderid, p_artid)
  CONSTRAINT u12;
